### PR TITLE
Fixed all scan topics to use front/scan.

### PR DESCRIPTION
**Pull request by tonybaltovski**

### CODE REVIEW

**Review by jyang-cpr — APPROVED** [review]
LGTM

**Comment by civerachb-cpr** [comment]
Is this an accidental duplicate of https://github.com/husky/husky/pull/268?

**Comment by tonybaltovski** [comment]
@civerachb-cpr that one was for noetic and this is for melodic.

**Review by luis-camero — COMMENTED** [review]
Looks good. 
In the future, we should probably add the scan_topic as an argument into `move_base.launch` and add `subst_value="True"` to the rosparam load:
https://github.com/husky/husky/blob/noetic-devel/husky_navigation/launch/move_base.launch#L41

So that the  cost-map common `obstacles_laser` laser gets its topic updated automatically: 
https://github.com/husky/husky/blob/noetic-devel/husky_navigation/config/costmap_common.yaml#L21

**Pull request merged**
