### PR TITLE
Move interactive marker launch from teleop into control launch file

### PR DESCRIPTION
**Pull request by paulbovbel**
@mikepurvis, thoughts?

Would like to align on details like this, with the hope of eventually transitioning to a standard bringup scheme for ros_control'ed platforms

### CODE REVIEW

**Comment by UltronDestroyer** [comment]
_control_ is different from _interaction_. the control.launch is meant to spawn controllers and control configurations. 

I'd suggest an interactions launch file/package if we are going to move things around. I do agree that the interactive_marker_server does not fit in with the teleop code/configs, since moving it with markers isn't teleop it is interaction.

**Comment by paulbovbel** [comment]
@TheDash, by convention, *control has been anything that is common to the platform's real and simulated operation. Have you fixed that regression yet?

**Comment by UltronDestroyer** [comment]
_control has been anything that is common to the platform's real and simulated operation_

Sorry, I'm lost here. control should be what the name says it is, bringing up controls/control configs. Since the interactive markers are interacting with a control/control configs and aren't really the things doing the back-end, we should keep it separate. It also gives the users the options to respawn interactions without having to bring down an entire control scheme for the robot.

imho i've always observed the convention to be what i've talked about above. If it's wrong, or different, it should probably change because mixing user inputs with robot-backend code is not elegant. just my 2c.

On the contrary to my point, I would support bringing this type of code into the control.launch/control.yaml simply because there isn't enough interaction code to justify a separation effort.

**Comment by mikepurvis** [comment]
I'm of two minds about it. There are definitely cases where we've ended up with more packages than necessary, so I'm loathe to create another package (per-platform) that'll basically just be a launch file.

Paul's logic above is what led `jackal_control` to contain not only the controller yamls, but also the localization and teleop ones: https://github.com/jackal/jackal/tree/indigo-devel/jackal_control/config

Interactive markers are extra fun because there's a case to be made that those should be run on the machine running rviz, rather than the robot— in the event that those are not the same machine, it should be cmd_vel going over the air, _not_ the marker feedback topic.

PR2 has a lot more packages for these kinds of things, but it also has a lot more complexity in terms of its configuration, for obvious reasons. I'm happy to have this stuff in `husky_control`, but we should establish some kind of a guideline which prevents `xx_control` packages from just becoming dumping grounds for stuff which is unable to find a home elsewhere.

**Comment by paulbovbel** [comment]
Hmm, agreed on the cmd_vel-over-the-air point

**Comment by mikepurvis** [comment]
The opposite case is that it's nice if `view_robot.launch` isn't having to launch mountains of stuff on top of rviz + a config. It's annoying to have that extra delay every time you re-launch. That was what tipped me over to launching the marker server on the robot rather than desktop, at least for Jackal on Indigo. But I'm not married to that— it can certainly be revisited in the future.

**Comment by paulbovbel** [comment]
Torn. From support requests, users want to have the twist marker available with real robot and simulation. There's also no guarantee (or requirement) that they continue to use our pre-baked husky_viz configs.

**Comment by rgariepy** [comment]
Personally, I rarely use any *_viz configs...

**Comment by UltronDestroyer** [comment]
Since the user will only ever use interactive markers when RViz is brought up, the conditions to which they use RViz is: they're on a desktop and want to see the robot either through sim or real. However, the design would then come down to, do we include all widgets and doo-hickeys on a standard RViz launch?

Something like this comes to mind:

roslaunch husky_viz view_robot interactive:=true 

However, interaction should only be enabled if the user intends to teleop it. Which, originally, makes sense why the interactive markers come up only on the teleop.launch file. Perhaps we keep this inside the teleop.launch file and allow the user to determine their own intent with interactive:=true parameter. It would be a UI design/User experience issue to decide if the interactive param default is false or true, though.

or perhaps:

roslaunch husky_teleop teleop.launch interaction:=true (but that feels clunky and not where it should be)

On Mike's point:

....That was what tipped me over to launching the marker server on the robot rather than desktop, at least for Jackal on Indigo...

We can specify what computer the node launches on using the machine tag. If the interaction node is launched on the desktop, and only published marker positions to the teleop node launched on the robot, I don't see that being too big of an issue. Alternatively, we can disable marker publishing over the network by passing in an interaction:=false parameter.

As a user of ROS software, and user experience/personal perspective:

Keep the interactive markers enabled by default, and they should spawn during default configs of the robot bringup in RViz. I want as little manual configuration as possible and maximum use of the robot on start-up.

**Comment by paulbovbel** [comment]
I think that's making it a little complex.

The reasoning for this change is that:
- many users ditch the rviz configs in favour of vanilla command line bringup (`rviz`), meaning we can't depend on the _viz launch file to start any nodes.
- we want interactive markers to run in both real and sim environments, all the time. There is little-to-no overhead if the markers aren't subscribed/controlled.
- control.launch is a reasonable place to start the node

**Comment by paulbovbel** [comment]
Going to merge since this makes sense for now, open to re-evaluation later during a RP robot launch architecture sync.

**Pull request merged**
