### PR TITLE
Added env var to allow a 7cm forward bumper extension

### PR DESCRIPTION
**Pull request by guystoppi**

### CODE REVIEW

**Comment by tonybaltovski** [comment]
@jeff-o Is this what you had in mind for the bumper extension?

**Comment by tonybaltovski** [comment]
@Nirzvi1 we'd prefer to input a value for the extension length rather than true/false for a fixed value.

**Comment by guystoppi** [comment]
@tonybaltovski 
The env var is now used as the length of the extension in centimetres, defaulting to zero.

**Comment by tonybaltovski** [comment]
Thanks @Nirzvi1 !

**Pull request merged**
