### PR TITLE
Custom husky tuning fixes

### PR DESCRIPTION
**Pull request by efernandez**
@p6chen 

This should probably be merged into `indigo-devel` too.

FYI @servos

### CODE REVIEW

**Comment by efernandez** [comment]
ping

**Comment by p6chen** [comment]
Looks good. We can merge this first. 

I'd hold off merging into indigo-devel until we do some robot tests just in case.

**Comment by efernandez** [comment]
OK, make sense. Should I create the PR for `indigo-devel`, so we don't forget about this? Or the plan is to have the target branch of this PR merged into `indigo-devel`at some point?

**Comment by efernandez** [comment]
I don't have write access to merge this PR.

@mikepurvis @p6chen I think you can merge it.

**Comment by efernandez** [comment]
ping

... or just give me access to merge :)

**Pull request merged**
